import math


#--- CAMERA ---
CAMERA_DISTANCE_TO_CENTER_INITIAL = 10.0

CAMERA_VIEW_CLIP_NEAR = 2.0

CAMERA_VIEW_CLIP_FAR = 720.0

SCALE_INITIAL = 5.0

SCALE_MIN = 0.1  # 0.5

SCALE_MAX = 20   # 8.0

SCALE_SPEED_FACTOR = 0.2

ROTATE_SPEED = 1.0

ROTATE_VERTICAL_MIN = 0 # 5

ROTATE_VERTICAL_MAX = 180  # 85

ROTATE_VERTICAL_INITIAL = 45


#--- PLANET ---
SEGMENT_SIZE = 5.0

PLANET_EQUATOR_SEGMENTS = 360

PLANET_EQUATOR_LENGTH = SEGMENT_SIZE * PLANET_EQUATOR_SEGMENTS

PLANET_RADIUS = PLANET_EQUATOR_LENGTH / (2.0 * math.pi)

SEGMENT_ANGLE = 360.0 / PLANET_EQUATOR_SEGMENTS

SEGMENT_ANGLE_HALF = SEGMENT_ANGLE / 2.0

SEGMENT_ANGLE_HALF_RADIANS = math.radians(SEGMENT_ANGLE_HALF)

SEGMENT_HALF_SIN = math.sin(SEGMENT_ANGLE_HALF_RADIANS)

SEGMENT_HALF_COS = math.cos(SEGMENT_ANGLE_HALF_RADIANS)

SEGMENT_ANGLE_RADIANS = math.radians(SEGMENT_ANGLE/math.sqrt(2.0))

SEGMENT_SIN = math.sin(SEGMENT_ANGLE_RADIANS)

SEGMENT_COS = math.cos(SEGMENT_ANGLE_RADIANS)

PI_4_SIN = math.sin(math.pi / 4.0)

PI_4_COS = math.cos(math.pi / 4.0)

VISIBLE_AREA_SIZE_SEGMENTS = 36

VISIBLE_AREA_SIZE_SEGMENTS_HALF = int(VISIBLE_AREA_SIZE_SEGMENTS / 2.0)

MODELS_SCALE_FACTOR = 1.0

LAND_MOVE_SPEED = 0.5

LAND_ROTATE_SPEED = 1.0


#--- ELEVATION ---
ELEVATION_FACTOR = PLANET_RADIUS * 0.2

ELEVATION_CORRECTION = 2.0

INPUT_WATER_LEVEL = 20

ELEVATION_UNPACK_EXPONENT = 2.0

ELEVATION_UNPACK_UNDERWATER_FACTOR = 50.0

WATER_LEVEL = 11

WATER_LEVEL_ELEVATION = PLANET_RADIUS + (WATER_LEVEL / 100.0) * ELEVATION_FACTOR
